## 113356046 夏永紳
---

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

---

#### Question 1

In [3]:
A = np.arange(36)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


#### Question 2

In [4]:
A_even = A[::2]
print(A_even)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


#### Question 3

In [5]:
B = A
B[1::2] = -1
print(B)


[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1
 24 -1 26 -1 28 -1 30 -1 32 -1 34 -1]


#### Question 4

In [6]:
A = A.reshape(6, 6)
B = B.reshape(6, 6)
print(A)
print(B)

[[ 0 -1  2 -1  4 -1]
 [ 6 -1  8 -1 10 -1]
 [12 -1 14 -1 16 -1]
 [18 -1 20 -1 22 -1]
 [24 -1 26 -1 28 -1]
 [30 -1 32 -1 34 -1]]
[[ 0 -1  2 -1  4 -1]
 [ 6 -1  8 -1 10 -1]
 [12 -1 14 -1 16 -1]
 [18 -1 20 -1 22 -1]
 [24 -1 26 -1 28 -1]
 [30 -1 32 -1 34 -1]]


#### Question 5

In [7]:
C = np.vstack((A, B))
print(C)

[[ 0 -1  2 -1  4 -1]
 [ 6 -1  8 -1 10 -1]
 [12 -1 14 -1 16 -1]
 [18 -1 20 -1 22 -1]
 [24 -1 26 -1 28 -1]
 [30 -1 32 -1 34 -1]
 [ 0 -1  2 -1  4 -1]
 [ 6 -1  8 -1 10 -1]
 [12 -1 14 -1 16 -1]
 [18 -1 20 -1 22 -1]
 [24 -1 26 -1 28 -1]
 [30 -1 32 -1 34 -1]]


#### Question 6

In [8]:
D = np.hstack((A, B))
print(D)


[[ 0 -1  2 -1  4 -1  0 -1  2 -1  4 -1]
 [ 6 -1  8 -1 10 -1  6 -1  8 -1 10 -1]
 [12 -1 14 -1 16 -1 12 -1 14 -1 16 -1]
 [18 -1 20 -1 22 -1 18 -1 20 -1 22 -1]
 [24 -1 26 -1 28 -1 24 -1 26 -1 28 -1]
 [30 -1 32 -1 34 -1 30 -1 32 -1 34 -1]]


#### Question 7

In [9]:
E = D.transpose()
print(E)


[[ 0  6 12 18 24 30]
 [-1 -1 -1 -1 -1 -1]
 [ 2  8 14 20 26 32]
 [-1 -1 -1 -1 -1 -1]
 [ 4 10 16 22 28 34]
 [-1 -1 -1 -1 -1 -1]
 [ 0  6 12 18 24 30]
 [-1 -1 -1 -1 -1 -1]
 [ 2  8 14 20 26 32]
 [-1 -1 -1 -1 -1 -1]
 [ 4 10 16 22 28 34]
 [-1 -1 -1 -1 -1 -1]]


#### Question 8

In [ ]:
def compute_stats(matrix):
    stats = {
        'sum': np.sum(matrix),
        'mean': np.mean(matrix),
        'std': np.std(matrix),
        'max': np.max(matrix),
        'min': np.min(matrix),
        'sum_rows': np.sum(matrix, axis=1),
        'sum_cols': np.sum(matrix, axis=0)
    }
    return stats
print(compute_stats(A))
print(compute_stats(B))
print(compute_stats(C))
print(compute_stats(D))
print(compute_stats(E))

{'sum': 288, 'mean': 8.0, 'std': 11.61177563223357, 'max': 34, 'min': -1, 'sum_rows': array([ 3, 21, 39, 57, 75, 93]), 'sum_cols': array([ 90,  -6, 102,  -6, 114,  -6])}
{'sum': 288, 'mean': 8.0, 'std': 11.61177563223357, 'max': 34, 'min': -1, 'sum_rows': array([ 3, 21, 39, 57, 75, 93]), 'sum_cols': array([ 90,  -6, 102,  -6, 114,  -6])}
{'sum': 576, 'mean': 8.0, 'std': 11.61177563223357, 'max': 34, 'min': -1, 'sum_rows': array([ 3, 21, 39, 57, 75, 93,  3, 21, 39, 57, 75, 93]), 'sum_cols': array([180, -12, 204, -12, 228, -12])}
{'sum': 576, 'mean': 8.0, 'std': 11.61177563223357, 'max': 34, 'min': -1, 'sum_rows': array([  6,  42,  78, 114, 150, 186]), 'sum_cols': array([ 90,  -6, 102,  -6, 114,  -6,  90,  -6, 102,  -6, 114,  -6])}
{'sum': 576, 'mean': 8.0, 'std': 11.61177563223357, 'max': 34, 'min': -1, 'sum_rows': array([ 90,  -6, 102,  -6, 114,  -6,  90,  -6, 102,  -6, 114,  -6]), 'sum_cols': array([  6,  42,  78, 114, 150, 186])}


#### Question 9

In [ ]:
print(np.max(A, axis=1)[0])


4


#### Question 10

In [20]:
print(np.min(B,axis=1)[0])

-1


#### Question 11

In [22]:
print(np.mean(C,axis=1)[0])

0.5


#### Question 12

In [23]:
print(np.std(D,axis=1)[0])


1.8929694486000912


#### Question 13

In [24]:
print(np.max(A,axis=1)[1])


10


#### Question 14

In [25]:
print(np.min(B,axis=1)[1])


-1


#### Question 15

In [26]:
print(np.mean(C,axis=1)[1])



3.5


#### Question 16

In [27]:
print(np.std(D,axis=1)[1])

4.645786621588784


#### Question 17

In [28]:
print(np.cumsum(E, axis=1))

[[  0   6  18  36  60  90]
 [ -1  -2  -3  -4  -5  -6]
 [  2  10  24  44  70 102]
 [ -1  -2  -3  -4  -5  -6]
 [  4  14  30  52  80 114]
 [ -1  -2  -3  -4  -5  -6]
 [  0   6  18  36  60  90]
 [ -1  -2  -3  -4  -5  -6]
 [  2  10  24  44  70 102]
 [ -1  -2  -3  -4  -5  -6]
 [  4  14  30  52  80 114]
 [ -1  -2  -3  -4  -5  -6]]


#### Question 18

In [29]:
print(np.cumsum(E, axis=0))

[[  0   6  12  18  24  30]
 [ -1   5  11  17  23  29]
 [  1  13  25  37  49  61]
 [  0  12  24  36  48  60]
 [  4  22  40  58  76  94]
 [  3  21  39  57  75  93]
 [  3  27  51  75  99 123]
 [  2  26  50  74  98 122]
 [  4  34  64  94 124 154]
 [  3  33  63  93 123 153]
 [  7  43  79 115 151 187]
 [  6  42  78 114 150 186]]


#### Question 19

In [ ]:
def sum_rows(arr):
    return np.sum(arr, axis=1)
arr = np.random.rand(2, 3, 4)
print(sum_rows(arr))

[[1.91610728 1.47243211 0.989834   0.99754202]
 [0.41879104 1.38588618 1.53462038 1.34556159]]
