## 113356046
---

In [1]:
import numpy as np

### 1

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


### 2

In [3]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3

In [4]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


### 4

In [5]:
d = np.ones((2, 2, 3))
print(d)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### 5

In [8]:
A = np.arange(100).reshape(10, 10)
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### 6

In [9]:
B = A.T
print(B)

[[ 0 10 20 30 40 50 60 70 80 90]
 [ 1 11 21 31 41 51 61 71 81 91]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 3 13 23 33 43 53 63 73 83 93]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 5 15 25 35 45 55 65 75 85 95]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 7 17 27 37 47 57 67 77 87 97]
 [ 8 18 28 38 48 58 68 78 88 98]
 [ 9 19 29 39 49 59 69 79 89 99]]


### 7

In [10]:
print(A[7, 9])

79


### 8

In [11]:
print(B[7,9])

97


### 9

In [12]:
print(A[2, :])

[20 21 22 23 24 25 26 27 28 29]


### 10

In [13]:
print(B[-1:])

[[ 9 19 29 39 49 59 69 79 89 99]]


### 11

In [14]:
print(A[7:10, :])

[[70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### 12

In [15]:
print(B[5:7,:])

[[ 5 15 25 35 45 55 65 75 85 95]
 [ 6 16 26 36 46 56 66 76 86 96]]


### 13

In [20]:
res = A[[0,2,3,6,8], 5:10]
print(res.T)

[[ 5 25 35 65 85]
 [ 6 26 36 66 86]
 [ 7 27 37 67 87]
 [ 8 28 38 68 88]
 [ 9 29 39 69 89]]


### 14

In [22]:
res = A[6,[1,3,6,8,9]]
print(res)

[61 63 66 68 69]


### 15

In [24]:
res = A[[1,2,3,4,5,8],[0,2,4,6,8,9]]
print(res)

[10 22 34 46 58 89]
